linrongbin16/fzfx.nvim

- bin/files/provider.lua
- bin/live_grep/provider.lua
- lua/fzfx/color.lua
- lua/fzfx/config.lua
- lua/fzfx/helpers.lua
- lua/fzfx/module.lua
- lua/fzfx/shell_helpers.lua
colors based on doc: https://man.archlinux.org/man/fzf.1.en
```
EXAMPLES:
fzf --color='bg:237,bg+:236,info:143,border:240,spinner:108' \
--color='hl:65,fg:252,header:65,fg+:252' \
--color='pointer:161,marker:168,prompt:110,hl+:108'
fzf --color='bg:#4B4B4B,bg+:#3F3F3F,info:#BDBB72,border:#6B6B6B,spinner:#98BC99' \
--color='hl:#719872,fg:#D9D9D9,header:#719872,fg+:#D9D9D9' \ --color='pointer:#E12672,marker:#E17899,prompt:#98BEDE,hl+:#98BC99'
```
We can assume:
* `bg` (background): `Normal` bg (`s:dark_bg`)
* `bg+` (background current line): `CursorLine` bg
* `info` (info line: right side numbers): `PreProc` fg
* `border` (border): `Ignore` bg (not sure, `s:dark_bg + 3`, candidates: `MatchParen`, `Ignore`, `DiffChange`)
* `spinner` (input indicator: > ): `Statement` bg (not sure, candidates: …
> feat: colors

- lua/fzfx/launch.lua
- lua/tests/minimal_powershell_init.lua
Fix https://github.com/linrongbin16/fzfx.nvim/issues/74
> fix: shell opts for Windows

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- lua/fzfx/config.lua
> perf: reduce CommandConfig

- README.md
> doc: deprecate InteractionConfig

- .github/workflows/ci.yml
- lua/fzfx/config.lua
- lua/fzfx/general.lua
- lua/fzfx/schema.lua
> deprecate: remove CommandConfig from config

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- lua/fzfx/actions.lua
- lua/fzfx/config.lua
- lua/fzfx/files.lua
- lua/fzfx/live_grep.lua
- test/actions_spec.lua
> fix: edit files actions on path containing whitespaces for fd/find/eza/ls results

- lua/fzfx/general.lua
- lua/fzfx/schema.lua
- test/actions_spec.lua
- test/general_spec.lua
> refactor(schema): add 'ProviderConfig' detection

- lua/fzfx/config.lua
- lua/fzfx/files.lua
- lua/fzfx/general.lua
- lua/fzfx/git_files.lua
- lua/fzfx/live_grep.lua
- lua/fzfx/schema.lua
- test/general_spec.lua
> refactor(schema): deprecate 'ProviderConfig'

- lua/fzfx/general.lua
- test/general_spec.lua
> feat(schema): add 'PreviewerConfig' detection

- lua/fzfx/schema.lua
> perf(schema): deprecate note on 'PreviewerConfig'

- .github/workflows/ci.yml
> ci: conventional commits

- .github/workflows/ci.yml
> ci(pr): only run conventional commits check on PR

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/ci.yml
- lua/fzfx/actions.lua
- lua/fzfx/line_helpers.lua
- test/actions_spec.lua
> fix(actions): 'bdelete' filename containing whitespaces

- .github/workflows/ci.yml
- lua/fzfx/config.lua
- lua/fzfx/constants.lua
- lua/fzfx/module.lua
> refactor(config): rewrite live grep providers

- lua/fzfx/utils.lua
> fix(utils): transform windows newline '\r\n' & close all 3 handles

- lua/fzfx/actions.lua
- lua/fzfx/config.lua
- lua/fzfx/utils.lua
- test/actions_spec.lua
> test(actions): add test cases for 'git_checkout'

- .github/workflows/ci.yml
- bin/rpc/client.lua
> ci(pr): auto format with stylua

- bin/general/previewer.lua
- bin/general/provider.lua
- lua/fzfx/shell_helpers.lua
- test/shell_helpers_spec.lua
> feat(logs): split shell command provider/previewer logs

- bin/rpc/client.lua
> fix(bin): setup log at first

- README.md
> docs(commands): update variants

- lua/fzfx/general.lua
> chore: remove deadcode

- .github/workflows/ci.yml
- .gitignore
- lua/fzfx.lua
- lua/fzfx/actions.lua
- test/actions_spec.lua
- test/minimal_fzfx_action_not_found_init.lua
- test/minimal_init.lua
- test/minimal_packer_init.lua
- test/minimal_powershell_init.lua
- test/minimal_termguicolors_init.lua
> perf(test): improve test coverage

- README.md
> docs(config): more schema details

- lua/fzfx/actions.lua
- lua/fzfx/ui.lua
- test/actions_spec.lua
- test/fzf_helpers_spec.lua
- test/ui_spec.lua
> feat(actions): require user confirm to discard modified buffer when jump to other files

- lua/fzfx/ui.lua
> fix(actions): suppress 'ctrl-c' cancel error

- README.md
- bin/rpc/notify.lua
- bin/rpc/request.lua
- lua/fzfx.lua
- lua/fzfx/config.lua
- lua/fzfx/fzf_helpers.lua
- lua/fzfx/general.lua
- lua/fzfx/module.lua
- lua/fzfx/popup.lua
- lua/fzfx/previewer_labels.lua
- lua/fzfx/server.lua
- lua/fzfx/yank_history.lua
- test/general_spec.lua
- test/previewer_labels_spec.lua
> feat(preview): add label for rg/grep preview window

- lua/fzfx/config.lua
- lua/fzfx/fzf_helpers.lua
- lua/fzfx/general.lua
- lua/fzfx/previewer_labels.lua
- test/config_spec.lua
- test/previewer_labels_spec.lua
> feat(preview): add vim commands, keymaps previewer label

- lua/fzfx/config.lua
- lua/fzfx/line_helpers.lua
- lua/fzfx/previewer_labels.lua
- test/line_helpers_spec.lua
- test/previewer_labels_spec.lua
> feat(preview): add label for file explorer

- lua/fzfx/general.lua
> fix(rpc): release rpc registries after fzf exit

- bin/general/fzfport.lua
- lua/fzfx/general.lua
- lua/fzfx/line_helpers.lua
- lua/fzfx/previewer_labels.lua
> fix(rg): fix column missing error

- lua/fzfx/config.lua
> fix(git_commits): fix wrong current buffer checking

- lua/fzfx/actions.lua
- lua/fzfx/popup.lua
> fix(actions): fix ctrl-c abort error, improve actions error message

- lua/fzfx/ui.lua
> fix(prompt): respect `hidden` option when open files

- lua/fzfx/config.lua
- lua/fzfx/general.lua
> feat(config): add global `override_fzf_opts` with highest priority

- README.md
> chore(docs): add 'override_fzf_opts' to config

- .luacheckrc
- README.md
- lua/fzfx.lua
- lua/fzfx/config.lua
- test/config_spec.lua
> feat(lsp_incoming_calls): add `FzfxLspIncomingCalls`

- lua/fzfx/cfg/_lsp.lua
- lua/fzfx/cfg/_lsp_locations.lua
- lua/fzfx/cfg/lsp_definitions.lua
- lua/fzfx/cfg/lsp_diagnostics.lua
- lua/fzfx/config.lua
- lua/fzfx/helper/providers.lua
- test/cfg/_lsp_locations_spec.lua
> perf(config): migrate to 'cfg.lsp_definitions'

- bin/general/provider.lua
- lua/fzfx/cfg/buffers.lua
- lua/fzfx/cfg/git_files.lua
- lua/fzfx/cfg/git_live_grep.lua
- lua/fzfx/cfg/live_grep.lua
- lua/fzfx/cfg/lsp_definitions.lua
- lua/fzfx/cfg/lsp_diagnostics.lua
- lua/fzfx/cfg/lsp_implementations.lua
- lua/fzfx/cfg/lsp_incoming_calls.lua
- lua/fzfx/cfg/lsp_outgoing_calls.lua
- lua/fzfx/cfg/lsp_references.lua
- lua/fzfx/cfg/lsp_type_definitions.lua
- lua/fzfx/detail/general.lua
- lua/fzfx/schema.lua
> perf(config): migrate to provider decorators

- lua/fzfx/config.lua
- lua/fzfx/detail/general.lua
- lua/fzfx/detail/popup.lua
- test/detail/popup_spec.lua
> perf(configs): support 'win_opts' as lua function

- lua/fzfx/config.lua
- lua/fzfx/detail/general.lua
> fix(configs): fix 'win_opts' recalculation

- lua/fzfx/cfg/buffers.lua
Fix https://github.com/linrongbin16/fzfx.nvim/issues/522
Fix https://github.com/linrongbin16/fzfx.nvim/issues/495
> fix(buffers): don't try to show unloaded buffers

- lua/fzfx/cfg/buffers.lua
fix #528.
relate #526, #522
- Use `V`/`W`/`P`/`R` variants (visual selection, cursor …
> fix(buffers): revert unload buffers change

- README.md
> chore(docs): format

- lua/fzfx/config.lua
- lua/fzfx/detail/fzf_helpers.lua
> fix(icons): fix fzf pointer/marker icons disable

- lua/fzfx/detail/popup/buffer_popup_window.lua
> fix(buffer previewer): reset to first line when previewing a file

- .github/workflows/ci.yml
- lua/fzfx/detail/popup/buffer_popup_window.lua
> ci(luarocks): fix luarocks package

- lua/fzfx.lua
- lua/fzfx/config.lua
- lua/fzfx/detail/fzf_helpers.lua
- lua/fzfx/detail/general.lua
- lua/fzfx/detail/popup.lua
- spec/detail/fzf_helpers_spec.lua
> fix(colors): fix static fzf color & icon opts

- bin/general/provider.lua
> chore(provider): improve debug logging

- lua/fzfx/cfg/buffers.lua
- lua/fzfx/cfg/git_files.lua
- lua/fzfx/detail/general.lua
- lua/fzfx/detail/popup/buffer_popup_window.lua
> feat(config): enable buffer previewers 2

- lua/fzfx/cfg/buffers.lua
- lua/fzfx/detail/general.lua
> fix(buffers): fix 'ctrl-d' interactions in Windows

- lua/fzfx/detail/popup/buffer_popup_window.lua
> perf(previewer): longer intervals when rendering buffer previewer

- COMMAND.html
- README.md
> docs(usage): improve commands section

- .github/PULL_REQUEST_TEMPLATE.md
- lua/fzfx/helper/previewer_labels.lua
> fix(marks): only show filename when exists

- .github/workflows/ci.yml
- lua/fzfx/detail/popup/buffer_popup_window.lua
- lua/fzfx/detail/popup/fzf_popup_window.lua
> ci(release): fix permission

- lua/fzfx/detail/popup/buffer_popup_window.lua
> feat(opts): respect 'wrap' option in fzf option '--preview-window'

- lua/fzfx/detail/bat_helpers.lua
> perf(bat): clean-up inaccurate @lsp & @treesitter colors from bat theme

- lua/fzfx/detail/popup/buffer_popup_window.lua
> fix(preview): fix buffer previewer on scrolling small file

- lua/fzfx/detail/popup/buffer_popup_window.lua
> perf(buffer previewer): reduce rendering latency on big file

- lua/fzfx/cfg/git_live_grep.lua
> feat(git live grep): use buffer previewer

- lua/fzfx/cfg/buf_live_grep.lua
- lua/fzfx/helper/previewers.lua
- spec/helper/previewers_spec.lua
> feat(buf live grep): use buffer previewer

- lua/fzfx/detail/popup/buffer_popup_window.lua
- lua/fzfx/detail/popup/fzf_popup_window.lua
- lua/fzfx/detail/popup/popup_helpers.lua
- minimal_init/buffers_autosize_init.lua
- minimal_init/fzf_color_opts_init.lua
- minimal_init/preview_window_opts_init.lua
- spec/detail/popup/popup_helpers_spec.lua
> refactor(popup): refactor cursor relative window layout

- lua/fzfx/cfg/lsp_diagnostics.lua
> feat(lsp diagnostics): use buffer previewer

- lua/fzfx/detail/general.lua
- lua/fzfx/detail/module.lua
- lua/fzfx/lib/env.lua
> refactor(env): remove 'cache_dir' env var

- .github/workflows/ci.yml
- lua/fzfx.lua
- lua/fzfx/detail/bat_helpers.lua
- lua/fzfx/helper/bat_themes.lua
> perf(bat): immediately build bat themes after initialize

- lua/fzfx/detail/popup/buffer_popup_window.lua
> refactor(previewer): rename internal field in buffer previewer

- lua/fzfx/detail/popup/buffer_popup_window.lua
> feat(previewer): respect 'number' options

- lua/fzfx/detail/popup/buffer_popup_window.lua
> fix(previewer): avoid preview window flush

- lua/fzfx/cfg/_lsp_locations.lua
- lua/fzfx/detail/popup/popup_helpers.lua
> feat(popup): move to upper side if bottom has not enough space

- README.md
- lua/fzfx/health.lua
- spec/health_spec.lua
> feat(health): add health check

- lua/fzfx/health.lua
- spec/health_spec.lua
> refactor(health): refactor checkhealth

- .github/workflows/ci.yml
- docs/KnownIssues.md
- docs/_sidebar.md
- lua/fzfx/cfg/_lsp_locations.lua
- lua/fzfx/detail/general.lua
- lua/fzfx/lib/lsp.lua
- lua/fzfx/schema.lua
- spec/cfg/_lsp_locations_spec.lua
- spec/lib/lsp_spec.lua
> refactor(lsp locations): part 4

- lua/fzfx/cfg/lsp_diagnostics.lua
- spec/cfg/lsp_diagnostics_spec.lua
> refactor(diagnostic): part 9

- lua/fzfx/helper/previewer_labels.lua
- spec/helper/previewer_labels_spec.lua
> refactor(previewer_labels): part 15

- docs/ApiReferences/fzfx_helper.md
- docs/ApiReferences/fzfx_lib.md
- docs/_sidebar.md
- lua/fzfx/cfg/_lsp_locations.lua
- lua/fzfx/cfg/buf_live_grep.lua
- lua/fzfx/cfg/buffers.lua
- lua/fzfx/cfg/file_explorer.lua
- lua/fzfx/cfg/files.lua
- lua/fzfx/cfg/git_blame.lua
- lua/fzfx/cfg/git_commits.lua
- lua/fzfx/cfg/git_files.lua
- lua/fzfx/cfg/git_live_grep.lua
- lua/fzfx/cfg/git_status.lua
- lua/fzfx/cfg/live_grep.lua
- lua/fzfx/cfg/lsp_diagnostics.lua
- lua/fzfx/cfg/vim_commands.lua
- lua/fzfx/cfg/vim_keymaps.lua
- lua/fzfx/cfg/vim_marks.lua
- lua/fzfx/helper/previewers.lua
- spec/cfg/git_status_spec.lua
- spec/cfg/vim_marks_spec.lua
- spec/helper/previewers_spec.lua
- spec/schema_spec.lua
> refactor(previewers): part 16

- .markdownlint.jsonc
- README.md
- lua/fzfx/detail/bat_helpers.lua
- lua/fzfx/helper/bat_themes.lua
- lua/fzfx/helper/previewers.lua
- lua/fzfx/lib/switches.lua
- spec/lib/switches_spec.lua
> feat(bat)!: add bat theme autogen switch, by default disabled

- bin/previewer.lua
- bin/provider.lua
- lua/fzfx/cfg/_lsp_locations.lua
- lua/fzfx/cfg/buf_live_grep.lua
- lua/fzfx/cfg/buffers.lua
- lua/fzfx/cfg/file_explorer.lua
- lua/fzfx/cfg/files.lua
- lua/fzfx/cfg/git_files.lua
- lua/fzfx/cfg/git_live_grep.lua
- lua/fzfx/cfg/live_grep.lua
- lua/fzfx/cfg/lsp_diagnostics.lua
- lua/fzfx/cfg/vim_command_history.lua
- lua/fzfx/cfg/vim_commands.lua
- lua/fzfx/cfg/vim_keymaps.lua
- lua/fzfx/cfg/vim_marks.lua
- lua/fzfx/detail/general.lua
- lua/fzfx/detail/popup.lua
- lua/fzfx/detail/popup/buffer_popup_window.lua
- lua/fzfx/detail/popup/fzf_popup_window.lua
- lua/fzfx/schema.lua
- spec/detail/general_spec.lua
- spec/schema_spec.lua
> refactor: rename "PreviewerTypeEnum"

- docs/ApiReferences/fzfx_helper.md
- docs/ApiReferences/fzfx_lib.md
- docs/Demo.md
- docs/GenericSchema.md
- docs/How.md
- docs/README.md
- docs/Sponsor.md
- docs/Why.md
- docs/_sidebar.md
- docs/index.html
- lua/fzfx/schema.lua
- spec/schema_spec.lua
> refactor: remove "PreviewerLabelTypeEnum"

- lua/fzfx/detail/bat_helpers.lua
It seems a more precisely theme generation needs 3 layers:
1. Regex color
2. Treesitter Color
3. LSP token color
This PR adds regex color as a very fundamental fallback for all colors, to keep it correct when user don't have LSP or treesitter.
Here's few images to show the difference between buffer previewer (**left**) and bat auto-generated theme (**right**):
- Monokai ColorScheme
<p align="center">
</p>
- GitHub Dark ColorScheme
<p align="center">
</p>
- Gruvbox ColorScheme 
<p align="center">
</p>
Related discussion: https://github.com/linrongbin16/fzfx.nvim/discussions/770
> feat(bat): more precisely bat theme generation

- lua/fzfx/detail/bat_helpers.lua
- spec/detail/bat_helpers_spec.lua
Related discussion: https://github.com/linrongbin16/fzfx.nvim/discussions/770
Once the bat theme auto-generation (based on Regex + TreeSitter + LSP token) is quite compatbile with nvim colorscheme, I will fully drop the "buffer previewer" feature, thus reduce the maintainance and future development effort to make this plugin neat and clean.
I will bump this plugin to v8.x to announce the break changes.
> feat(bat): more precisely bat themes with LSP token

- lua/fzfx/helper/previewers.lua
The `$FZF_PREVIEW_COLUMN` environment variable cannot be detected on windows platform, so for now we disable the "git-delta" support on windows and fallback to default git diff.
> fix(git): disable git-delta on windows platform

- docs/GenericSchema.md
- lua/fzfx/cfg/file_explorer.lua
- lua/fzfx/cfg/vim_commands.lua
- lua/fzfx/cfg/vim_keymaps.lua
- lua/fzfx/cfg/vim_marks.lua
- lua/fzfx/detail/general.lua
- lua/fzfx/helper/previewers.lua
- lua/fzfx/schema.lua
- spec/cfg/vim_marks_spec.lua
This PR adds a hook function "context_shutdown" that recycles resources allocated during search. It works like a GC that collects resources allocated, for example some temporary files.
This PR also delete all the temporary files while searching, thus no extra disk is been used after searching is complete.
> feat(context): add "context_shutdown" hook to recycle resources on search complete
