linrongbin16/fzfx.nvim

- bin/buffers/provider.lua
- bin/files/provider.lua
- bin/git_files/provider.lua
- bin/live_grep/provider.lua
- lua/fzfx/actions.lua
- lua/fzfx/config.lua
- lua/fzfx/constants.lua
- lua/fzfx/shell_helpers.lua
- lua/fzfx/utils.lua
> fix: edit grep

- README.md
- lua/fzfx/command.lua
- lua/fzfx/config.lua
- lua/fzfx/constants.lua
- lua/fzfx/launch.lua
- lua/fzfx/schema.lua
> fix: grep exclude hiddens

- README.md
- lua/fzfx/config.lua
- lua/fzfx/module.lua
- lua/fzfx/object.lua
- lua/tests/minimal_packer_nvim_init.lua
Fix: https://www.reddit.com/r/neovim/comments/162vfcf/comment/jy0jt9t/?context=3
> fix: packer.nvim

- lua/fzfx/popup.lua
> fix: set spell=false

- lua/fzfx/popup.lua
> fix: nonumber

- README.md
- lua/fzfx/config.lua
> feat: lsp diagnostics file path color

- lua/fzfx/config.lua
> refactor: easier overwrite default configs

- README.md
- lua/fzfx/config.lua
- test/log_spec.lua
> fix: check method support

- README.md
- lua/fzfx/line_helpers.lua
- test/line_helpers_spec.lua
- test/test path containing spaces.txt
- test/test path containing spaces/good bye world.lua
- test/test path containing spaces/hello world.lua
This reverts commit 449169597bbdb70d233a4ccadb2502116bcad0dd.
> Revert "fix: filepath with whitespaces (#219)"

- bin/general/previewer.lua
- bin/general/provider.lua
- lua/fzfx/cmd.lua
- lua/fzfx/log.lua
- lua/fzfx/shell_helpers.lua
- lua/fzfx/utils.lua
- test/cmd_spec.lua
- test/shell_helpers_spec.lua
- test/utils_spec.lua
This reverts commit 5c8d535a095f14cba338ffd896bd02b25e7d7920.
> Revert "refactor: improve AsyncCmd (#228)"

- README.md
Hi, thanks to your contribute, while please finish below tasks: …
> doc: advanced configuration

- .github/PULL_REQUEST_TEMPLATE.md
- lua/fzfx/buffers.lua
- lua/fzfx/config.lua
- lua/fzfx/schema.lua
Hi, thanks to your contribute, while please finish below tasks: …
> deprecate: InteractionConfig

- README.md
> doc: add missing FzfxGFiles

- .github/workflows/ci.yml
> feat: please-release

- CHANGELOG.md
- README.md
> doc: move 'Break Changes' to CHANGELOG

- lua/fzfx/config.lua
> fix(interactions): cd into directory containing spaces

- .github/workflows/ci.yml
> ci(nvim): lower required nvim version to v0.6

- README.md
- lua/fzfx/actions.lua
- lua/fzfx/config.lua
- lua/fzfx/line_helpers.lua
- test/actions_spec.lua
> feat(actions): add 'setqflist'

- .github/workflows/ci.yml
> ci(release): use checkout@v4

- README.md
- lua/fzfx.lua
- lua/fzfx/actions.lua
- lua/fzfx/config.lua
- lua/fzfx/line_helpers.lua
- test.txt
- test/line_helpers_spec.lua
> feat(keymaps): add 'FzfxKeyMaps' to search vim keymaps

- .github/workflows/ci.yml
- README.md
> fix(required): set minimal required Neovim version to 0.7

- README.md
> docs(require): wording

- .github/workflows/ci.yml
- lua/fzfx/config.lua
- lua/fzfx/fzf_helpers.lua
- lua/fzfx/line_helpers.lua
- lua/fzfx/module.lua
- lua/fzfx/path.lua
- test/actions_spec.lua
- test/fzf_helpers_spec.lua
- test/line_helpers_spec.lua
- test/path_spec.lua
> perf(path): add 'expand' option to normalize

- README.md
> docs(table): fix contents of table link

- README.md
- lua/fzfx/config.lua
> docs(config): improve configs & defaults

- README.md
> docs(config): wording

- README.md
> docs(example): ls example

- README.md
> docs(example): wording

- README.md
> docs(example): add demo

- README.md
- lua/fzfx/schema.lua
> docs(example): update demo

- README.md
> docs(demo): upgrade live grep demo with dynamic preview labels

- README.md
> docs(depends): wording

- README.md
> docs(revert): add notification for reverted preview-label

- .github/workflows/ci.yml
- README.md
- lua/fzfx/general.lua
> ci(luacheck): check main branch

- README.md
> docs(intro): wording

- README.md
> docs(badge): update badge

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- lua/fzfx/config.lua
- lua/fzfx/general.lua
> feat(variant): add resume last search variant to all commands

- .editorconfig
- lua/fzfx/path.lua
> perf(path): reduce duplicate lines

- README.md
> chore(docs): format

- README.md
> chore(docs): update demo

- test/minimal_packadd_init.lua
> perf(test): add 'packadd' minimal test case

- .github/workflows/luarocks.yml
> perf(ci): again first release luarocks

- .github/workflows/luarocks.yml
> perf(ci): upload luarocks again

- .github/workflows/luarocks.yml
> ci(luarocks): manual trigger upload

- README.md
> chore(docs): badge

- README.md
> chore(docs): wording

- docs/REFERENCES.md
> chore(docs): fix index.html js

- README.md
- docs/REFERENCES.md
- docs/index.html
> chore(docs): fix permanent link, update GenericSchema.md link

- lua/fzfx/helper/actions.lua
- test/helper/actions_spec.lua
> feat(actions): center cursor for 'rg'/'grep' edit actions

- README.md
> chore(docs): update badge

- README.md
> docs(breaks): please specify a version/tag to avoid break changes!

- README.md
> chore(docs): fix 'ls -1' example code

- README.md
- lua/fzfx/detail/fzf_helpers.lua
> perf(install): drop off 'junegunn/fzf' dependecy

- README.md
> chore(docs): requirements

- README.md
> docs(intro): slogan

- .github/workflows/ci.yml
- codecov.yml
> ci(codecov): fix codecov action

- .luacov
- codecov.yml
> ci(codecov): ignore commons library

- README.md
> docs: wording

- lua/fzfx/detail/popup/buffer_popup_window.lua
> perf(previewer): reduce buffer previewer latency

- README.md
> chore(docs): typing

- lua/fzfx/detail/fzf_helpers.lua
- spec/detail/fzf_helpers_spec.lua
- spec/detail/popup/popup_helpers_spec.lua
> feat(colors): support RGB color codes in 'fzf_color_opts'

- README.md
- docs/KnownIssues.md
> docs(development): replace 'luacheck' with 'selene', rename 'credit' to 'alternatives'

- .luacheckrc
> ci(lint): remove '.luacheckrc'

- README.md
> docs(config): fix 'FzfxLs' example

- README.md
> docs(alternatives): add telescope.nvim

- README.md
> docs(requirements): add 'curl' to mandatory requirements

- .github/workflows/ci.yml
> ci(release): remove auto tag

- README.md
> docs(demo): update live grep demo with buffer previewer

- README.md
> docs: api references wording

- README.md
> docs(install): fix screen shots for installing git on Windows

- README.md
> docs(keys): add 'FzfxMarks' to recommend key mappings

- README.md
> docs(require): add note about legacy version support

- README.md
> docs(require): typing

- .github/workflows/ci.yml
- lua/fzfx/cfg/_lsp_locations.lua
- lua/fzfx/cfg/vim_keymaps.lua
- lua/fzfx/config.lua
- lua/fzfx/detail/general.lua
- lua/fzfx/detail/popup.lua
- lua/fzfx/detail/popup/popup_helpers.lua
- lua/fzfx/helper/contexts.lua
- lua/fzfx/helper/previewer_labels.lua
- lua/fzfx/helper/provider_decorators/_prepend_icon.lua
- spec/config_spec.lua
> refactor: part 1

- README.md
> docs(install): comment plugin version/tag in installing instructions

- README.md
> docs(requirement): wording

- README.md
> docs(usage): wording

- README.md
> docs(api): update api references link

- README.md
> docs(support): writing

- README.md
> docs: fix readme demo

- bin/provider.lua
- lua/fzfx/cfg/_lsp_locations.lua
- lua/fzfx/cfg/lsp_definitions.lua
- lua/fzfx/cfg/lsp_implementations.lua
- lua/fzfx/cfg/lsp_references.lua
- lua/fzfx/cfg/lsp_type_definitions.lua
- lua/fzfx/detail/general.lua
- lua/fzfx/detail/popup.lua
- lua/fzfx/schema.lua
> feat(provider): support new "ASYNC_DIRECT" provider type
